"use strict";

// ==================== CONFIGURATION ====================

const CONFIG = {
    ollamaUrl: "http://localhost:11434/api/generate",
    model: "gemma4:31b-cloud",
    outputDir: "C:/Users/gurucool/Desktop/horoscope",
    temperature: 0.78,
    maxRetries: 3,
    concurrentLimit: 1,
};

const ZODIAC_SIGNS = [
    "Aries", "Taurus", "Gemini", "Cancer",
    "Leo", "Virgo", "Libra", "Scorpio",
    "Sagittarius", "Capricorn", "Aquarius", "Pisces",
];

const SIGN_META = {
    Aries: { ruler: "Mars", element: "Fire", compatibility: ["Leo", "Sagittarius"] },
    Taurus: { ruler: "Venus", element: "Earth", compatibility: ["Virgo", "Capricorn"] },
    Gemini: { ruler: "Mercury", element: "Air", compatibility: ["Libra", "Aquarius"] },
    Cancer: { ruler: "Moon", element: "Water", compatibility: ["Scorpio", "Pisces"] },
    Leo: { ruler: "Sun", element: "Fire", compatibility: ["Aries", "Sagittarius"] },
    Virgo: { ruler: "Mercury", element: "Earth", compatibility: ["Taurus", "Capricorn"] },
    Libra: { ruler: "Venus", element: "Air", compatibility: ["Gemini", "Aquarius"] },
    Scorpio: { ruler: "Mars", element: "Water", compatibility: ["Cancer", "Pisces"] },
    Sagittarius: { ruler: "Jupiter", element: "Fire", compatibility: ["Aries", "Leo"] },
    Capricorn: { ruler: "Saturn", element: "Earth", compatibility: ["Taurus", "Virgo"] },
    Aquarius: { ruler: "Saturn", element: "Air", compatibility: ["Gemini", "Libra"] },
    Pisces: { ruler: "Jupiter", element: "Water", compatibility: ["Cancer", "Scorpio"] },
};

// ==================== SIGN PERSONALITY PROFILES ====================

const SIGN_PERSONALITY = {
    Aries: {
        coreNature: "bold, impatient, pioneering, quick to ignite and quick to burn out",
        lifeTheme: "conquest, initiation, identity, being first",
        weakness: "impulsive decisions, short temper, abandoning things mid-way",
        bodyZone: "head, face, adrenal glands — stress shows in tension headaches",
        workStyle: "charges ahead alone, leads from the front, hates committees and slow consensus",
        loveStyle: "pursues hard, gets bored if unchallenged, needs a partner who pushes back",
        moneyStyle: "spends impulsively on excitement, earns well in bursts, poor at long-term saving",
        stressSignal: "aggression, physical restlessness, picking fights to discharge tension",
        uniquePhrase: "The fire in you does not ask permission — it moves.",
    },
    Taurus: {
        coreNature: "patient, sensual, stubborn, deeply attached to comfort and routine",
        lifeTheme: "security, pleasure, ownership, building something that lasts",
        weakness: "possessiveness, resistance to change even when change is necessary",
        bodyZone: "throat, neck, thyroid — tension lodges in the jaw and shoulders",
        workStyle: "slow and methodical, finishes what others abandon, resists pressure beautifully",
        loveStyle: "loyal to a fault, expresses love through acts of care and physical presence",
        moneyStyle: "conservative saver, excellent long-term investor, distrusts financial risk",
        stressSignal: "over-eating, hoarding, refusing to engage with conflict",
        uniquePhrase: "You do not move fast — you move right.",
    },
    Gemini: {
        coreNature: "curious, adaptable, quick-witted, emotionally inconsistent",
        lifeTheme: "communication, duality, knowledge, connecting ideas across worlds",
        weakness: "scattered focus, starting conversations they never finish, surface-level connections",
        bodyZone: "lungs, hands, shoulders, nervous system — anxiety manifests as breathlessness",
        workStyle: "thrives on variety and information, burns out in repetitive structure",
        loveStyle: "needs mental stimulation above all, falls fast, loses interest if under-stimulated",
        moneyStyle: "sporadic earner and spender, many income streams, easily distracted by novelty",
        stressSignal: "overthinking, talking compulsively, inability to sit still or make a decision",
        uniquePhrase: "Your mind sees connections others miss — the cost is finishing one thought at a time.",
    },
    Cancer: {
        coreNature: "deeply intuitive, nurturing, emotionally protective, prone to withdrawal",
        lifeTheme: "home, belonging, emotional safety, memory, roots",
        weakness: "mood dependency, holding grudges quietly, confusing care with control",
        bodyZone: "chest, stomach, digestive system — emotional stress hits the gut first",
        workStyle: "works best in trusted teams, remembers everything, resents being overlooked",
        loveStyle: "loves deeply and completely, requires emotional safety before fully opening",
        moneyStyle: "security-driven saver, invests in home and family, anxious about financial loss",
        stressSignal: "retreating into silence, emotional eating, dwelling on past hurt",
        uniquePhrase: "Your strength is the depth of what you feel — not a weakness to manage, a gift to direct.",
    },
    Leo: {
        coreNature: "magnetic, generous, proud, hungry for recognition and creative expression",
        lifeTheme: "self-expression, leadership, performance, legacy, being seen",
        weakness: "ego fragility when ignored, drama as a tool for attention, difficulty sharing the spotlight",
        bodyZone: "heart, upper back, spine — carries stress in the chest and posture",
        workStyle: "leads visibly, excels in roles with an audience, wilts in anonymous back-office work",
        loveStyle: "romantic and grand in gesture, expects devotion, gives generously when appreciated",
        moneyStyle: "spends on quality and status, earns well through personal brand and performance",
        stressSignal: "loud withdrawal, seeking external validation, theatrical displays of hurt",
        uniquePhrase: "You were not built to shrink into rooms — you were built to change them.",
    },
    Virgo: {
        coreNature: "analytical, precise, service-driven, quietly critical of self above all others",
        lifeTheme: "improvement, order, usefulness, craft, getting the details exactly right",
        weakness: "chronic over-analysis, difficulty accepting imperfection, anxiety masking as criticism",
        bodyZone: "digestive system, intestines, nervous system — worry hits the stomach",
        workStyle: "solves problems others cannot find, works quietly and thoroughly, hates sloppy work",
        loveStyle: "shows love through acts of service, careful not to over-commit until trust is certain",
        moneyStyle: "meticulous budgeter, researches every purchase, distrusts anything that sounds too easy",
        stressSignal: "obsessive fixing, nitpicking others, physical complaints with no clear medical cause",
        uniquePhrase: "Your precision is not perfectionism — it is the highest form of care.",
    },
    Libra: {
        coreNature: "diplomatic, aesthetic, partnership-oriented, deeply uncomfortable with conflict",
        lifeTheme: "balance, beauty, fairness, relationships, harmony at almost any cost",
        weakness: "chronic indecision, people-pleasing that breeds quiet resentment, avoidance of hard truths",
        bodyZone: "kidneys, lower back, skin — stress shows in skin flare-ups and lower back ache",
        workStyle: "excellent mediator and collaborator, struggles to lead when a decisive call is needed",
        loveStyle: "idealistic romantic, needs partnership to feel whole, gives more than they ask for",
        moneyStyle: "spends on beauty and experiences, earns through relationships and negotiation",
        stressSignal: "prolonged indecision, over-compromising, withdrawing while quietly seething",
        uniquePhrase: "True balance is not avoiding the hard side — it is holding both sides without collapsing.",
    },
    Scorpio: {
        coreNature: "intense, perceptive, fiercely private, transformative, all-or-nothing in everything",
        lifeTheme: "power, death and rebirth, hidden truth, deep bonding, transformation",
        weakness: "jealousy, inability to forgive betrayal, using silence as a weapon",
        bodyZone: "reproductive organs, pelvis, elimination system — stores unexpressed emotion physically",
        workStyle: "investigates deeply, works best with autonomy, excels in high-stakes environments",
        loveStyle: "bonds soul-deep or not at all, loyalty is absolute, betrayal is never forgotten",
        moneyStyle: "strategic with money, good at accumulating quietly, uses resources as power",
        stressSignal: "cold withdrawal, obsessive thinking, cutting people off without warning",
        uniquePhrase: "You do not change at the surface — when you transform, it goes all the way down.",
    },
    Sagittarius: {
        coreNature: "optimistic, freedom-loving, philosophical, blunt to the point of tactlessness",
        lifeTheme: "expansion, truth, adventure, belief systems, seeking meaning beyond the horizon",
        weakness: "over-promising, fleeing when commitment feels like a cage, unintentional bluntness",
        bodyZone: "hips, thighs, liver, sciatic nerve — tension accumulates in the hips and lower body",
        workStyle: "big-picture thinker, excels in strategy and teaching, struggles with admin and routine",
        loveStyle: "needs freedom within commitment, falls for intellectual equals, fears emotional claustrophobia",
        moneyStyle: "optimistic about money to a fault, spends on experiences and travel, earns through belief",
        stressSignal: "restlessness, lecturing others, disappearing into travel or philosophical rabbit holes",
        uniquePhrase: "Your optimism is not naivety — it is a decision to aim beyond what others call realistic.",
    },
    Capricorn: {
        coreNature: "disciplined, ambitious, self-reliant, emotionally guarded behind a calm exterior",
        lifeTheme: "achievement, legacy, status, mastery, proving worth through sustained effort",
        weakness: "workaholism, emotional suppression, equating rest with failure",
        bodyZone: "knees, bones, teeth, joints — carries long-term stress in the skeletal structure",
        workStyle: "climbs steadily and methodically, respects hierarchy until it stops serving the goal",
        loveStyle: "slow to open, loyal once committed, shows love through reliability not words",
        moneyStyle: "disciplined saver and long-term investor, views money as security and freedom",
        stressSignal: "over-working, dismissing emotions as weakness, physical exhaustion worn as a badge",
        uniquePhrase: "You do not need applause at the base of the mountain — you need it at the summit.",
    },
    Aquarius: {
        coreNature: "visionary, independent, humanitarian, emotionally detached in personal relationships",
        lifeTheme: "innovation, collective progress, rebellion against convention, intellectual freedom",
        weakness: "emotional unavailability, contrarian streak, detachment confused with wisdom",
        bodyZone: "ankles, calves, circulatory system — poor circulation and nervous system sensitivity",
        workStyle: "works best with creative freedom, excels in systems thinking and future planning",
        loveStyle: "values friendship in romance, needs intellectual equality, resists emotional dependency",
        moneyStyle: "invests in ideas and innovation, erratic with personal finances, generous to causes",
        stressSignal: "emotional shutdown framed as logic, radical position changes, withdrawing from community",
        uniquePhrase: "You see the world as it could be — that vision is only useful if you stay in it.",
    },
    Pisces: {
        coreNature: "empathic, imaginative, spiritually attuned, boundary-blurred and easily overwhelmed",
        lifeTheme: "transcendence, compassion, creativity, dissolution of ego, spiritual union",
        weakness: "absorbing others emotions as their own, escapism, difficulty with firm boundaries",
        bodyZone: "feet, lymphatic system, immune system — fatigue and illness linked to emotional overload",
        workStyle: "thrives in creative and healing fields, struggles in rigid corporate environments",
        loveStyle: "loves unconditionally and often unwisely, merges deeply, needs grounding from partners",
        moneyStyle: "generous to others before self, susceptible to emotional spending, benefits from structure",
        stressSignal: "withdrawal into fantasy, sleeping excessively, invisible emotional collapse",
        uniquePhrase: "Your sensitivity is not fragility — it is the ability to feel what others cannot name.",
    },
};

// ==================== TIME WINDOW POOLS (50+ variants) ====================

const TIME_WINDOWS = {
    earlyMorning: [
        "before 8am", "at first light", "in the pre-dawn quiet", "before the day gains weight",
        "in the opening hour", "while the morning is still cool", "at 7am sharp",
        "before 8:30am", "in the earliest part of your morning", "when the day is still forming",
    ],
    morning: [
        "before 9am", "in the quiet of the morning", "before 10am", "at dawn's edge",
        "before the morning routine breaks", "in the first half of the morning",
        "around 9:30am", "while the morning holds its clarity", "before 10:30am",
        "in the sharpest part of your morning",
    ],
    midMorning: [
        "between 9am and 11am", "mid-morning", "around 10am", "as the morning sharpens",
        "in the late morning window", "between 10 and noon", "around 10:45am",
        "as mid-morning settles", "when the morning hits its stride", "approaching 11am",
    ],
    noon: [
        "around midday", "as noon arrives", "at the midday pivot", "in the lunch window",
        "at the 12pm crossover", "when the clock reaches twelve", "at noon precisely",
        "in the midday gap", "as the morning hands over to afternoon", "at the day's midpoint",
    ],
    earlyAfternoon: [
        "just after noon", "around 1pm", "in the opening of the afternoon",
        "when the afternoon begins", "at 1:30pm", "as afternoon takes its first steps",
        "in the hour after lunch", "between noon and 2pm", "around 1:15pm",
        "when the afternoon is still fresh",
    ],
    afternoon: [
        "in the early afternoon", "between 1pm and 3pm", "after midday settles",
        "around 2pm", "as the afternoon unfolds", "past the midday mark",
        "around 2:30pm", "in the mid-afternoon window", "between 2 and 4pm",
        "when the afternoon is in full motion",
    ],
    lateAfternoon: [
        "between 3pm and 5pm", "in the late afternoon", "as the day softens",
        "around 4pm", "when the afternoon thins", "before the evening shift",
        "around 4:30pm", "in the final stretch of the afternoon", "between 4 and 6pm",
        "when the working day winds toward its close",
    ],
    evening: [
        "after 6pm", "as evening takes hold", "when the sun drops", "in the early evening",
        "around 7pm", "once the day quiets", "when work hours end",
        "around 6:30pm", "as the evening opens", "when the transition from day to night completes",
        "past 7pm", "in the first hour of evening",
    ],
};

// ==================== PHRASE ROTATION POOLS ====================

const PHRASE_POOLS = {
    careerMomentum: [
        "career traction improves",
        "work clarity increases",
        "professional momentum rises",
        "decisions favour progress",
        "work pace strengthens",
        "forward movement in your career solidifies",
        "professional ground firms underfoot",
        "output quality climbs noticeably",
        "your professional rhythm finds its stride",
        "work direction sharpens into focus",
        "occupational drive locks in",
        "the quality of your work output rises",
        "professional energy converts directly into results",
        "task completion accelerates",
        "your career signal strengthens",
    ],
    loveConnection: [
        "bonds deepen where honesty leads",
        "relational warmth builds through action",
        "emotional closeness grows when words are chosen carefully",
        "a real connection strengthens today",
        "intimacy increases where trust already exists",
        "the emotional bridge between you and someone close narrows",
        "partnership energy shifts into a more honest register",
        "love moves through gesture, not statement",
        "relational depth increases when you stop performing",
        "a meaningful exchange changes the dynamic",
        "connection solidifies through direct conversation",
        "the emotional distance between you and someone important closes",
        "romantic energy converts into something more durable",
        "attraction deepens through shared honesty",
        "the relational thread pulls tighter today",
    ],
    focusSharpens: [
        "concentration locks in",
        "mental clarity arrives without effort",
        "thinking becomes precise and useful",
        "the fog lifts and priorities become obvious",
        "cognitive sharpness peaks",
        "analytical power runs strong",
        "your thinking cuts through noise",
        "attention narrows to what actually matters",
        "focus lands where it is needed most",
        "intellectual bandwidth opens up",
        "the mind operates at close to full capacity",
        "distractions lose their grip",
        "thought quality improves noticeably",
        "your analytical edge is reliable today",
        "mental traction holds",
    ],
    avoidSpending: [
        "hold non-essential purchases until the end of the week",
        "financial patience pays off — defer the larger decision",
        "spending now costs more than the price tag suggests",
        "delay the purchase — the numbers change favourably later",
        "protect liquidity today",
        "the financial move looks better in two days",
        "avoid reactive spending",
        "money held now compounds faster than money spent now",
        "keep the wallet closed until clarity arrives",
        "the better financial moment is ahead, not today",
        "rushing this transaction adds hidden cost",
        "financial restraint now opens better options next week",
        "the impulse to spend is strong and worth resisting",
        "deferring this choice is the stronger financial move",
        "hold the line on spending — conditions improve shortly",
    ],
    energyPeak: [
        "physical output runs high",
        "stamina holds well",
        "body energy is reliable",
        "physical reserves are solid",
        "endurance is above your usual baseline",
        "vitality is present — use it deliberately",
        "the body co-operates today",
        "physical capacity is dependable",
        "strength and steadiness align",
        "energy levels are a genuine asset",
        "your body performs without resistance",
        "physical resilience holds across the day",
        "stamina converts directly into results if directed well",
        "the body is willing — the question is where you aim it",
        "physical energy peaks and the window is worth using",
    ],
    innerWorld: [
        "the part of you that watches quietly knows the answer already",
        "beneath the composed exterior, a decision is forming",
        "you carry more certainty than your hesitation suggests",
        "the inner voice that rarely speaks loudly is speaking now",
        "something in you has already resolved this — the mind is catching up",
        "there is a quieter version of this situation you have not yet looked at directly",
        "the self that operates behind your public face is the one that matters today",
        "you process more than you show — today that depth becomes useful",
        "the version of you that others see is not the one making the real decisions right now",
        "underneath the routine, something is being worked out",
        "a private recalibration is underway — others will not see it yet",
        "the most important conversation today is the one you have with yourself",
        "your instinct is ahead of your analysis on this one",
        "the thing you have not said aloud is closer to the truth than the thing you have",
        "you are more aware of the subtext of today than you are letting on",
    ],
    dualityPhrase: [
        "the same quality that makes you exceptional in this area is the one that complicates it",
        "your greatest asset today operates best when held with a light grip",
        "what looks like a weakness is actually an over-expression of your strongest trait",
        "the line between your gift and your blind spot runs directly through this situation",
        "today's challenge is a familiar one wearing a new face",
        "the trait that makes you successful here is also the one that costs you when overused",
        "your instinct is correct — the timing needs adjusting",
        "the pattern you recognise in this situation is real, not paranoia",
        "strength applied without awareness becomes its own obstacle",
        "the quality others admire in you is working against you in this specific context today",
        "your depth is an advantage — until it becomes a reason to avoid the surface decision",
        "confidence and caution are both available to you — today requires one more than the other",
        "the part of you that doubts and the part of you that knows are both right about different things",
        "your capacity here is not in question — only how you direct it",
        "the same drive that built your track record is the one nudging you too hard right now",
    ],
    hiddenDepth: [
        "the effort behind this goes untracked by most people in your life",
        "you think through things that others treat as settled",
        "the standard you hold yourself to is not visible to anyone watching",
        "the work that does not show is the work that holds everything else up",
        "most people in your position would have stopped caring by now",
        "the invisible scaffolding you maintain daily is more complex than it appears",
        "you carry context that others in this situation simply do not have",
        "the restraint you exercise today is not passivity — it is precision",
        "your contribution to this situation is larger than it is acknowledged to be",
        "the thought process behind your decisions is not available to anyone evaluating the outcome",
        "you see the second-order effects of this before most people notice the first",
        "the due diligence you apply here is not common — it just looks that way from outside",
        "your involvement in this adds value that cannot be easily quantified",
        "there is more happening in your internal processing today than your output reveals",
        "the care you bring to this is disproportionate to what anyone else would bring",
    ],
    resistanceGrowth: [
        "the friction here is not random — it is information",
        "what feels like resistance is the universe asking for precision, not more effort",
        "the obstacle is not blocking the path — it is shaping you for what the path requires",
        "the difficulty today is not punishment — it is preparation",
        "the discomfort is pointing at something worth understanding",
        "slow progress in this area is not failure — it is the correct pace for what is being built",
        "the setback is temporary; the lesson is permanent",
        "what looks like a closed door is a redirection",
        "the challenge is doing exactly what it is supposed to do",
        "the resistance you feel today is proportional to how much this matters",
        "difficulty in the short term is often the price of durability in the long term",
        "the harder version of this situation is the one that produces lasting change",
        "struggling with this is not a sign you are wrong — it is a sign you are engaged",
        "the pressure here is not destructive — it is forming something",
        "the universe does not present obstacles to people who are not ready to learn from them",
    ],
};

// ==================== PROMPT LEAK PATTERNS ====================

const PROMPT_LEAK_PATTERNS = [
    /\[[^\]]{3,}\]/,
    /\[Bold [^\]]+\]/i,
    /\[career peak\]/i,
    /\[After [^\]]+\]/i,
    /\[Insert [^\]]+\]/i,
    /direct statement/i,
    /direct work statement/i,
    /financial signal/i,
    /direct career signal/i,
    /direct relationship statement/i,
    /direct home energy statement/i,
    /direct energy statement/i,
    /direct financial signal/i,
    /barnum technique/i,
    /barnum-forer/i,
    /line 1:/i,
    /lines 2-4:/i,
    /final line:/i,
    /seo meta/i,
    /use this exact/i,
    /apply barnum/i,
    /word count/i,
    /narrative field/i,
    /seeded pick/i,
    /assigned time window/i,
    /apply techniques/i,
    /as instructed/i,
];

// ==================== FIELD TOPIC RULES ====================

const FIELD_TOPIC_RULES = {
    career: {
        label: "career",
        offTopicPatterns: [/romantic/i, /partner\b/i, /love life/i, /relationship tension/i, /stomach ache/i, /immune/i],
    },
    love: {
        label: "love",
        offTopicPatterns: [/quarterly report/i, /spreadsheet/i, /stock market/i, /your boss/i, /promotion/i],
    },
    moneyAndFinance: {
        label: "moneyAndFinance",
        offTopicPatterns: [/romantic/i, /love life/i, /heart chakra/i, /immune system/i],
    },
    health: {
        label: "health",
        offTopicPatterns: [/stock/i, /invest/i, /salary/i, /romantic/i, /love life/i, /quarterly/i],
    },
};

// ==================== COLOR NAME MAP ====================

const COLOR_NAMES = [
    { name: "Red", hex: "#DC143C" },
    { name: "Orange", hex: "#FF5733" },
    { name: "Yellow", hex: "#FFC200" },
    { name: "Green", hex: "#228B22" },
    { name: "Sky Blue", hex: "#14aff7ff" },
    { name: "Violet", hex: "#7B2FBE" },
    { name: "Pink", hex: "#FF69B4" },
    { name: "Teal", hex: "#008080" },
    { name: "Sienna", hex: "#E97451" },
    { name: "Blue", hex: "#191970" },
    { name: "Green", hex: "#20873dff" },
    { name: "Green", hex: "#1bf114ff" },
    { name: "Grey", hex: "#708090" },
    { name: "Turquoise", hex: "#40E0D0" },
    { name: "Magenta", hex: "#FF00FF" },
    { name: "Orange", hex: "#B7410E" },
    { name: "Blue", hex: "#0047AB" },
    { name: "Lavender", hex: "#E6D7FF" },
    { name: "Green", hex: "#50C878" },
    { name: "White", hex: "#ffffff" },
];

// ==================== NUMBER WORD MAP ====================

const NUMBER_WORDS = {
    1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five",
    6: "Six", 7: "Seven", 8: "Eight", 9: "Nine",
};

module.exports = {
    CONFIG,
    ZODIAC_SIGNS,
    SIGN_META,
    SIGN_PERSONALITY,
    TIME_WINDOWS,
    PHRASE_POOLS,
    PROMPT_LEAK_PATTERNS,
    FIELD_TOPIC_RULES,
    COLOR_NAMES,
    NUMBER_WORDS,
};
